version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: fiscalio-db
    restart: unless-stopped
    command: ['--max_allowed_packet=256M']
    environment:
      MARIADB_ROOT_PASSWORD: Solomid8
      MARIADB_DATABASE: fiscalio_prod
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - fiscalio_fiscalio-network

networks:
  fiscalio_fiscalio-network:
    external: true
